### ISSUE TITLE
Hello,i want to have your e-mail or some other contact information.

### ISSUE THREAD

**Issue by zzukun** [asher-stern/CRF#1]
Hi,
i am a student from China, and i am learning your CRF code.
But i can't get the training data --- Penn Tree-Bank corpus.
I know the corpus is not free, so I just want to get 10 - 20 sentence of the corpus for test.
could you copy some sentence to me for testing ? 
Thank you very much !

LiKun,Zhengzhou University,China

**Comment by zzukun** [comment]
My e-mail is likun@stu.zzu.edu.cn

**Comment by asher-stern** [comment]
Hi.
I don't have it either. I got a copy of PTB about a year ago to test my software, but I left it on my old PC, so I can't access it right now.

You say you are a student, so perhaps your professor can provide you this resource.

Good luck,
Asher

**Comment by zzukun** [comment]
Thank you all the same, i have find a sample from { http://www.nltk.org/nltk_data/  } , NO. 71 . 
After I import all of the Treebank data, there exist some error in calculating process, i am solving the problem now.

**Comment by fucusy** [comment]
I think you need to put the description about how to get the data if you have not added data into your git repository @asher-stern

**Comment by asher-stern** [comment]
@fucusy I myself don't know how to get the data (which is Penn Tree-Bank), but I guess that it is merely by contacting LDC.
