### ISSUE TITLE
Make sure values don't become non-finite 

### ISSUE THREAD

**Issue by cacfd3a** [asher-stern/CRF#3]
It can happen (it, in fact _has_ happened to me) that values calculated during the forward-backward algorithm become larger than [Double.MAX_VALUE](http://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#MAX_VALUE), and are represented using [POSITIVE_INFINITY](http://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#POSITIVE_INFINITY).

These are values we can't really compute with, leading to `NaN` values and wrecking our training procedure.

I would propose to use maximum finite double values in these cases. Add the following lines to `CrfUtilities.safeAdd()`:

```
if (variable == Double.POSITIVE_INFINITY) variable = Double.MAX_VALUE;
if (variable == Double.NEGATIVE_INFINITY) variable = -Double.MAX_VALUE;
```

And also provide a function `CrfUtilities.safeMultiply()`:

```
public static double safeMultiply(double variable, final double val2) {
    final double oldValue = variable;
    variable *= val2;
    if (variable == Double.POSITIVE_INFINITY) variable = Double.MAX_VALUE;
    if (variable == Double.NEGATIVE_INFINITY) variable = -Double.MAX_VALUE;
    if (!Double.isFinite(variable)) {
        //  Note that we have not added the check for ((val2 < 0.0) && (oldValue < variable)) || ((val2 > 0.0) && (oldValue > variable)), because floating point arithmetic is inexact
        throw new CrfException("Error: multiplying value to \"double\" variable yielded unexpected results. "
                + "variable was: " + String.format("%1$.3f", oldValue) + ", value to multiply was: " + String.format("%1$.3f", val2));
    }
    return variable;
}
```

And use these functions in all places where we do floating point calculations.

I don't know too much about the internals of this project, so I would like your feedback on this.

**Comment by asher-stern** [comment]
Hi.
Thanks for raising this issue.
I agree with your point, but I'm not sure I agree with the proposed solution. The reason is that, after all, the calculations might not result in right values, when values are artificially set to MAX_VALUE.

Perhaps java.math.BigDecimal is the appropriate solution here? However, this would require more-substantial changes.

Let's leave this issue opened, though I cannot guarantee it will be fixed in the near future.

Thanks,
Asher

**Comment by cacfd3a** [comment]
True. I felt that maybe for values that are so big, it doesn't matter whether they're accurate anymore.

But I'm no expert on CRFs nor floating point arithmetic.

It may be worthwhile to investigate what other people did ([IIT Bombay](http://crf.sourceforge.net/), [Mallet](http://mallet.cs.umass.edu/)).

**Comment by asher-stern** [comment]
OK.
If you find some interesting solutions of other people, I will be happy to hear.

Many thanks,
Asher.

**Comment by asher-stern** [comment]
Fixed.
Checks for infinity were added. In case of calculations that end up with infinity values, the L-BFGS code goes to a fall back of one-step of gradient ascent. Next iterations will use L-BFGS as usual.
